
# Uncomment this line to define a global platform for your project
platform :ios, ‘8.0’

target 'QZFinancialSupermarket' do
  pod 'AFNetworking', '~> 3.1.0'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'YYModel', '~> 1.0.4'
  pod 'SDWebImage', '~> 3.8.2'
  pod 'Masonry', '~> 1.0.2'
  pod 'IQKeyboardManager', '~> 4.0.8’
  pod 'JPush', '3.0.2'
  #自动侧或返回
#  pod 'FDFullscreenPopGesture','~> 1.1’
 
 pod 'MBProgressHUD','~> 1.0.0’
 pod 'SVProgressHUD','~> 2.1.2’
 pod 'TTTAttributedLabel','~> 2.0.0’
 pod 'FCUUID', '~> 1.3.1'




end

